# Generated by Django 6.0.2 on 2026-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_method',
            field=models.CharField(blank=True, choices=[('espresso', 'Espresso'), ('filter', 'Filter'), ('french_press', 'French Press'), ('pour_over', 'Pour Over'), ('aeropress', 'AeroPress'), ('moka_pot', 'Moka Pot'), ('cold_brew', 'Cold Brew')], default='', max_length=50),
        ),
    ]
