# Generated by Django 6.0.2 on 2026-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_city_alter_profile_favorite_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='in_season',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bean',
            name='roaster',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Tasting',
        ),
    ]
