# Generated by Django 6.0.4 on 2026-04-24 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bean_in_season_bean_roaster_delete_tasting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('bean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastings', to='base.bean')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tastings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
